[replacements]
comment = [
    ["/listings/", "/listings-sources/"]
]
only_commented = [
    ["/listings-sources/", "/listings/"],
]

[ignore_rows]
only_commented = [
    "<!-- markdownlint-disable -->",
    "<!-- markdownlint-restore -->"
]
